"""Add Google OAuth fields

Revision ID: 94d11a90f05d
Revises: cd912f8866b7
Create Date: 2025-10-16 09:51:24.356670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d11a90f05d'
down_revision = 'cd912f8866b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###