"""add_activity_logs_table_new

Revision ID: de6eb00baabf
Revises: fe3244c480e0
Create Date: 2025-10-16 15:43:24.357042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de6eb00baabf'
down_revision = 'fe3244c480e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###