"""Add activity logs table

Revision ID: fe3244c480e0
Revises: 94d11a90f05d
Create Date: 2025-10-16 10:16:43.590969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe3244c480e0'
down_revision = '94d11a90f05d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###